# conda env create -f environment.yml
# mamba env create -f environment.yml
name: sail_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - ipykernel
  - ipyleaflet
  - leafmap
  - ipywidgets
  - jupyterlab
  - jupyterlab_widgets
  - matplotlib
  - seaborn
  - ipympl
  - numpy
  - pandas
  - pip
  - requests
  - scipy
  - setuptools_scm
  - pytorch
  - torchvision
  - tensorflow
  - tensorboard
  - scikit-learn # checkpoint
  - aiohttp
  - aiobotocore
  - boto3
  - bokeh
  - dask
  - earthaccess
  - hvplot
  - holoviews
  - h5py
  - h5netcdf 
  - jupyter
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyter_bokeh
  - gdal=3.7
  - geoviews
  - netcdf4
  - pystac-client
  - pandas
  - pyproj
  - pyresample
  - rioxarray
  - rasterio
  - ray-default
  - scikit-image
  - shapely
  - spectral
  - zarr
  - proj-data
  - proj
  - sliderule
  - laspy
  - pyntcloud
  - contextily
  - xarray
  - rioxarray
  - rasterio
  - pathlib
  - netCDF4
  - affine
  - bottleneck
  - metpy
  - planetary_computer
  - opencv
  - branca
  - jinja2
  - folium
  - pillow
  - pip:
      - numexpr
      - pylas
      - "deephyper[ray,torch]"
